theme: jekyll-theme-minimal
#remote_theme: joshgerdes/jekyll-uno

title: Jacob Pettit
description: This is my resume style landing page. I also have a <a href="https://jfpettit.svbtle.com/">blog</a>.
logo: GPTempDownload-1.JPG

