title: Jacob Pettit
author: Jacob Pettit
baseurl: '/'
description: My personal website.
profile_url: "https://jfpettit.github.io"

markdown: kramdown
highlighter: rouge

plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
  - jemoji

kramdown:
  input: GFM
  auto_ids: true
  syntax_highlighter: rouge

permalink: /blog/:year/:month/:day/:title
