theme: jekyll-theme-minimal
#remote_theme: joshgerdes/jekyll-uno

title: Jacob Pettit
description: My resume style page. I also <a href="https://jfpettit.svbtle.com/">blog</a>.
logo: GPTempDownload-1.JPG

